apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::631367023556:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12QAQU5RXTISE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::631367023556:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-01T22:36:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1606"
  uid: 420e28cf-9ef9-480a-8bdd-95184e265313
